name: Movecraft-Cannons
version: ${project.version}
main: net.tylers1066.movecraftcannons.MovecraftCannons
api-version: 1.13
depend: [Movecraft, Cannons]
softdepend: [Movecraft-Combat]
authors: [TylerS1066]
description: Integration between Movecraft-Combat and Cannons
