name: Java CI

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '22 19 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft-Cannons
      uses: actions/checkout@v2
      with:
        path: Movecraft-Cannons
    - name: Checkout Movecraft-Combat
      uses: actions/checkout@v2
      with:
        repository: 'TylerS1066/Movecraft-Combat'
        path: Movecraft-Combat
        ref: 'main'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Movecraft-Combat
    - name: Build Movecraft-Combat
      run: mvn -B package -T 1C --file Movecraft-Combat/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # Build Movecraft-Cannons
    - name: Build Movecraft-Cannons
      run:  mvn -B package -T 1C --file Movecraft-Cannons/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage jar
      run: mkdir staging && cp Movecraft-Cannons/target/Movecraft-Cannons*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Cannons*.jar staging/Movecraft-Cannons_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: MC-Cannons_Dev-Build
        path: staging/Movecraft-Cannons_*.jar
